### ISSUE TITLE
Monero Error is not defined

### ISSUE THREAD

**Issue by HCPioquinto** [monero-ecosystem/monero-javascript#42] opened 2020-09-21 18:33 UTC
Please send help (My lvl: noob-grammer),

I ran into some issues earlier (which did not happen before) when creating New Wallet WASM. It seems to return a MoneroError but the problem is that I tried to catch it and says MoneroError is not defined (I think it's when it is creating a new Config as per the log file).

Just a quick question also. Does this have issues when the Library is called via Workers? I implemented workers that will handle each walletWasm opening as we are trying to open an array of wallets (which is a killer for my laptop).

Log error: 
```
ReferenceError: MoneroError is not defined
    at new MoneroWalletConfig (/home/hcpioquinto/Desktop/work_files/Monero_backup/node_modules/monero-javascript/src/main/js/wallet/model/MoneroWalletConfig.js:45:9)
    at Function.createWallet (/home/hcpioquinto/Desktop/work_files/Monero_backup/node_modules/monero-javascript/src/main/js/wallet/MoneroWalletWasm.js:176:62)
    at Object.module.exports.createWalletWasm (/home/hcpioquinto/Desktop/work_files/Monero_backup/node_modules/monero-javascript/index.js:183:87)
    at MoneroWalletsHandler.createNewWallet (/home/hcpioquinto/Desktop/work_files/Monero_backup/moneroAPIClass.js:218:38)
    at MoneroWalletsHandler.onCreateWalletRequest (/home/hcpioquinto/Desktop/work_files/Monero_backup/moneroAPIClass.js:195:18)
    at /home/hcpioquinto/Desktop/work_files/Monero_backup/moneroAPIClass.js:307:20
    at Array.forEach (<anonymous>)
    at MoneroWalletsHandler.onImportWallets (/home/hcpioquinto/Desktop/work_files/Monero_backup/moneroAPIClass.js:301:23)
    at initThread (/home/hcpioquinto/Desktop/work_files/Monero_backup/newServer.js:124:38)
    at Object.<anonymous> (/home/hcpioquinto/Desktop/work_files/Monero_backup/newServer.js:137:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:162:24)
    at MessagePort.emit (events.js:315:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
```

**Comment by woodser** [comment] 2020-09-21 18:46
Thanks for pointing out the issue with MoneroError.  That's fixed in https://github.com/monero-ecosystem/monero-javascript/commit/1e2900070fda06d78ab93ecda88a287d98d39a86.

> Does this have issues when the Library is called via Workers?

By default, the library will run all WASM wallets in a single web worker off the main thread.  I believe running multiple wallets in multiple workers runs into the issue of concurrent daemon requests interfering with each other, but maybe there is a way around that.

**Comment by HCPioquinto** [comment] 2020-09-21 23:20
I did what  you said and let the WASMs run on their own and not to a specified Worker.  Thanks a ton.

Another quick question: Why does Memory object out of etc whatever will display when you are attempting to open/create two wallets at once

**Comment by HCPioquinto** [comment] 2020-09-21 23:27
```
RuntimeError: memory access out of bounds
```
Here's the issue when trying to open two wallets at once

**Comment by woodser** [comment] 2020-09-22 13:55
> Why does Memory object out of etc whatever will display when you are attempting to open/create two wallets at once

I'm not able to reproduce an error by creating or opening multiple wallets at once, with or without await.  Can you elaborate how you're creating it?

**Comment by HCPioquinto** [comment] 2020-09-22 16:25
Probably due to my weak computer so not particularly sure regarding that one. But what I basically did was have an array of at least 2 wallets with { mnemonic, heght} then attempt to recover it by looping like

```
// Sample code
wallets.map( wallet => {
    const walletConfig = {
         path: pathjs.join(walletsDir, mnemonicHash),
          mnemonic: wallet.mnemonic,
        restoreHeight: wallet.height
   };
     monerojs.createWalletWasm( walletConfig)
   }):

^ Kind of pseudo coding here but I think you get the idea
```

Then the memory access out of bounds will display.

**Comment by HCPioquinto** [comment] 2020-09-22 16:31
While we are at it a quick question:

I am currently doing like a way to open a wallet first then save it later to a specified path as I intend to use the hashed mnemonic of that wallet as the filename of the WASMs to be saved.

I was thinking of doing either:
a.) Open wallet, get mnemonic, close without saving then restore (in which I think it's not efficient but willing to be corrected)
b.) Open wallet, get mnemonic, set path, save using the path. (in which I was checking the code is not possible for now?) and this is my first choice but is there a way to set a path after a wallet WASM is created?? Thanks a ton @woodser

**Comment by woodser** [comment] 2020-09-30 18:36
I'm still not able to reproduce the memory access out of bounds error.  `monerojs.createWalletWasm(...)` returns a promise which needs to be awaited/resolved before the wallet is fully initialized.  Perhaps that's the problem?

I added support for [MoneroWalletWasm.moveTo(path)](https://moneroecosystem.org/monero-javascript/MoneroWalletWasm.html#moveTo) (committed to master) which can save the wallet after being created in-memory.  Hope that resolves your issue?

**Comment by woodser** [comment] 2021-02-05 13:39
Closing this since the original issue is resolved.  Please open another issue if further help is needed.

**Closed by woodser** 2021-02-05 13:39 UTC
